name: flutter_social_share_plugin
description: Flutter Plugin for sharing contents to social media.You can use it share to Facebook , WhatsApp , Twitter And System Share UI. Support Url and Text.
version: 1.0.3
homepage: https://github.com/KhilanVitthani/flutter_social_share/

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.6.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface:



  # The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.flutter_social_share
        pluginClass: FlutterSocialSharePlugin
      ios:
        pluginClass: SwiftFlutterSocialSharePlugin